//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceMapDotNetTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SourceMapDotNetTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:3,&quot;file&quot;:&quot;Library.js&quot;,&quot;sourceRoot&quot;:&quot;&quot;,&quot;sources&quot;:[&quot;Library.ts&quot;],&quot;names&quot;:[&quot;SourceMaps&quot;,&quot;SourceMaps.Library&quot;,&quot;SourceMaps.Library.MathUtil&quot;,&quot;SourceMaps.Library.MathUtil.constructor&quot;,&quot;SourceMaps.Library.MathUtil.Add&quot;,&quot;SourceMaps.Library.MathUtil.IsEven&quot;,&quot;SourceMaps.Library.MathUtil.StaticAdd&quot;,&quot;SourceMaps.Library.MathUtil.StaticIsEven&quot;],&quot;mappings&quot;:&quot;AAAA,IAAO,UAAU;AA0BhB,CA1BD,UAAO,UAAU;KAAjBA,UAAkBA,OAAOA;QACrBC;YAAAC;YAwBAC,CAACA;AAAAD,YAvBGA,yBAAAA,UAAWA,KAAaA,EAAEA,MAAcA;gBACpCE,OAAOA,KAAKA,GAAGA,MA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Library_js {
            get {
                return ResourceManager.GetString("Library_js", resourceCulture);
            }
        }
    }
}
